import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthContextProvider from "../context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

//.. metadata objesi ve generateMetadata fonksiyonu sadece Server Componentlerden export edilebilir.

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Navbar />
          {children}
        </AuthContextProvider>
      </body>
      {/* Bütün sayfaları kapsayan layout burasıdır. */}
    </html>
  );
}
